"""inicial"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taxa_pct', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxa_fixa', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('documento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kwh', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('hora_trabalho', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('falhas_pct', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margem_pct', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impressora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('watts', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vida_h', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('horas_acumuladas', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('manutencao_h', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unidade', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custo_unit', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('minimo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('minimo_g', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movestoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('obs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movestoque_item_id'), 'movestoque', ['item_id'], unique=False)
    op.create_index(op.f('ix_movestoque_item_tipo'), 'movestoque', ['item_tipo'], unique=False)
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arquivo_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('foto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('peso_g', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tempo_min', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feita', sa.Boolean(), nullable=False),
    sa.Column('recorrencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_nome'), 'usuario', ['nome'], unique=True)
    op.create_table('orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('validade_dias', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frete', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prazo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pagamento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canal.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('foto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('tempo_min', sa.Integer(), nullable=False),
    sa.Column('impressora_id', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margem_pct', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('minimo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('embalagem', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('acessorios', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_trabalho', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['impressora_id'], ['impressora.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produto_sku'), 'produto', ['sku'], unique=True)
    op.create_table('rolo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('peso_inicial', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('preco', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comprado_em', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('personalizacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('preco_unit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('custo_unit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('canal_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('observacoes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frete', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('custo_extra', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('do_estoque', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canal.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_status'), 'pedido', ['status'], unique=False)
    op.create_table('produtoinsumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('qtd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtomaterial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('gramas', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidohistorico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('de', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('para', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidoitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('personalizacao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('preco_unit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('custo_unit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('canal_id', sa.Integer(), nullable=True),
    sa.Column('forma_pagamento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('custo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxa', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('lucro', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canal.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('natureza', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('pago_em', sa.Date(), nullable=True),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('recorrencia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gerou_proximo', sa.Boolean(), nullable=False),
    sa.Column('cancelado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendaitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('preco_unit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('custo_unit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendaitem')
    op.drop_table('lancamento')
    op.drop_table('venda')
    op.drop_table('pedidoitem')
    op.drop_table('pedidohistorico')
    op.drop_table('produtomaterial')
    op.drop_table('produtoinsumo')
    op.drop_index(op.f('ix_pedido_status'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_table('item')
    op.drop_table('rolo')
    op.drop_index(op.f('ix_produto_sku'), table_name='produto')
    op.drop_table('produto')
    op.drop_table('orcamento')
    op.drop_index(op.f('ix_usuario_nome'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('tarefa')
    op.drop_table('projeto')
    op.drop_index(op.f('ix_movestoque_item_tipo'), table_name='movestoque')
    op.drop_index(op.f('ix_movestoque_item_id'), table_name='movestoque')
    op.drop_table('movestoque')
    op.drop_table('material')
    op.drop_table('insumo')
    op.drop_table('impressora')
    op.drop_table('config')
    op.drop_table('cliente')
    op.drop_table('canal')
    # ### end Alembic commands ###
