"""custos_fixos"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('custos_fixos_mes', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0'))
    op.add_column('config', sa.Column('horas_mes', sa.Numeric(precision=14, scale=2), nullable=False, server_default='160'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'horas_mes')
    op.drop_column('config', 'custos_fixos_mes')
    # ### end Alembic commands ###
