"""lote_fornecedor"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insumo', sa.Column('fornecedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('produto', sa.Column('preco_manual', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('produto', sa.Column('lote_qtd', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('produto', sa.Column('fornecedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('rolo', sa.Column('fornecedor', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rolo', 'fornecedor')
    op.drop_column('produto', 'fornecedor')
    op.drop_column('produto', 'lote_qtd')
    op.drop_column('produto', 'preco_manual')
    op.drop_column('insumo', 'fornecedor')
    # ### end Alembic commands ###
