"""qtd_pronta"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidoitem', sa.Column('qtd_pronta', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidoitem', 'qtd_pronta')
    # ### end Alembic commands ###
